steps:

- script: echo "##vso[task.setvariable variable=PY_EXE]$(python -c 'import sys; print(sys.executable)')"
  displayName: Set Python Path
  PYTHONWARNINGS: 'ignore:DEPRECATION'

- script: |
    pip install certifi
    echo "##vso[task.setvariable variable=GIT_SSL_CAINFO]$(python -m certifi)"
    echo "##vso[task.setvariable variable=LANG]C.UTF-8"
    echo "##vso[task.setvariable variable=PIP_PROCESS_DEPENDENCY_LINKS]1"

- script: $PY_EXE -m pipenv install --deploy --dev
  env:
    PY_EXE: $(PY_EXE)
    GIT_SSL_CAINFO: $(GIT_SSL_CAINFO)
    LANG: $(LANG)
    PIP_PROCESS_DEPENDENCY_LINKS: $(PIP_PROCESS_DEPENDENCY_LINKS)
    PIPENV_DEFAULT_PYTHON_VERSION: $(PIPENV_DEFAULT_PYTHON_VERSION)
    PYTHONWARNINGS: 'ignore:DEPRECATION'
    PIPENV_VERBOSITY: '-1'
    PIPENV_NOSPIN: '1'
  displayName: Make Virtualenv
